# Generated by Django 3.2.6 on 2021-08-13 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('royalcontrol', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='endereco',
            field=models.JSONField(null=True),
        ),
    ]
