# Generated by Django 3.2.6 on 2021-08-13 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('royalcontrol', '0003_alter_empresa_endereco'),
    ]

    operations = [
        migrations.AddField(
            model_name='controle',
            name='tipo',
            field=models.CharField(default=None, max_length=12),
            preserve_default=False,
        ),
    ]
